### ISSUE TITLE
No bookings for bookingId reported by a payment

### ISSUE THREAD

**Issue by bkniffler** [BookingSync/bookingsync-api-docs#337]
I'm fetching payments via `/payments` endpoint. Using the bookingId found in `links.bookings`, I'm then trying to fetch the associated booking(s). But a lot of the time, even though there are bookingIds, I won't get any result from the api.

Example:
`https://www.bookingsync.com/api/v3/payments/8676799` => `links.bookings: [14172881]`
`https://www.bookingsync.com/api/v3/bookings/14172881` => no bookings

How comes?

**Comment by Azdaroth** [comment]
Hi @bkniffler , most likely these are past or canceled bookings, please check http://developers.bookingsync.com/reference/endpoints/bookings/, especially the parts regarding `from` and `include_canceled` query params

**Comment by bkniffler** [comment]
it works with include_canceled=true

But it doesn't make sense to me that if I explicitly request an item by id `/bookings/:id`, I still need to provide include_canceled.
